binary_path: demo_assets/manipulation/RAIManipulationDemo/RAIManipulationDemo.GameLauncher
level: RoboticManipulationBenchmark
required_simulation_ros2_interfaces:
  services:
      - /spawn_entity
      - /delete_entity
  topics:
      - /color_image5
      - /depth_image5
      - /color_camera_info5
  actions: []
required_robotic_ros2_interfaces:
  services:
      - /detection
      - /segmentation
      - /manipulator_move_to
  topics: []
  actions: []
